const WIKI_SOURCE = "https://cs.wikipedia.org/wiki/Seznam_dopravn%C3%ADch_zna%C4%8Dek_v_%C4%8Cesku";

const commons = (fileName) => `https://commons.wikimedia.org/wiki/Special:FilePath/${fileName}`;

const svgDataUrl = (markup, width = 320, height = 220) =>
  `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${markup}</svg>`,
  )}`;

const roadSvg = (markup) =>
  svgDataUrl(
    `
      <rect width="320" height="220" rx="24" fill="#dfe6ec"/>
      <rect x="28" y="28" width="264" height="164" rx="18" fill="#4d5157"/>
      ${markup}
    `,
  );

const tableSvg = (markup) =>
  svgDataUrl(
    `
      <rect width="320" height="220" rx="24" fill="#f3efe8"/>
      <rect x="46" y="52" width="228" height="116" rx="10" fill="white" stroke="#1c1c1c" stroke-width="6"/>
      ${markup}
    `,
  );

const horizontalImages = {
  v1a: roadSvg(`<rect x="156" y="44" width="8" height="140" rx="4" fill="white"/>`),
  v2a: roadSvg(`
    <rect x="156" y="52" width="8" height="22" rx="4" fill="white"/>
    <rect x="156" y="90" width="8" height="22" rx="4" fill="white"/>
    <rect x="156" y="128" width="8" height="22" rx="4" fill="white"/>
  `),
  v5: roadSvg(`<rect x="74" y="106" width="172" height="10" rx="5" fill="white"/>`),
  v6b: roadSvg(`
    <rect x="74" y="112" width="172" height="10" rx="5" fill="white"/>
    <text x="160" y="94" text-anchor="middle" fill="white" font-size="34" font-weight="800">STOP</text>
  `),
  v7a: roadSvg(`
    <rect x="88" y="60" width="18" height="100" fill="white"/>
    <rect x="118" y="60" width="18" height="100" fill="white"/>
    <rect x="148" y="60" width="18" height="100" fill="white"/>
    <rect x="178" y="60" width="18" height="100" fill="white"/>
    <rect x="208" y="60" width="18" height="100" fill="white"/>
  `),
  v8a: roadSvg(`
    <rect x="80" y="98" width="20" height="24" rx="5" fill="white"/>
    <rect x="116" y="98" width="20" height="24" rx="5" fill="white"/>
    <rect x="152" y="98" width="20" height="24" rx="5" fill="white"/>
    <rect x="188" y="98" width="20" height="24" rx="5" fill="white"/>
    <circle cx="130" cy="86" r="16" fill="none" stroke="#4d5157" stroke-width="10"/>
  `),
  v9a: roadSvg(`
    <path d="M120 150V88h-18l58-44 58 44h-18v62h-24v-44h-32v44z" fill="white"/>
  `),
  v12b: roadSvg(`
    <path d="M90 76l140 68M230 76L90 144" stroke="#ffd23f" stroke-width="18" stroke-linecap="round"/>
  `),
  v14: roadSvg(`
    <rect x="122" y="42" width="76" height="136" rx="10" fill="#be2330"/>
    <path d="M140 150V92h-12l30-22 30 22h-12v58z" fill="white"/>
    <circle cx="158" cy="78" r="12" fill="none" stroke="white" stroke-width="8"/>
  `),
  v15: roadSvg(`<text x="160" y="120" text-anchor="middle" fill="white" font-size="42" font-weight="800">STOP</text>`),
};

const supplementaryImages = {
  e1: tableSvg(`<text x="160" y="126" text-anchor="middle" fill="#111" font-size="54" font-weight="800">3×</text>`),
  e3a: tableSvg(`
    <path d="M84 112h112" stroke="#111" stroke-width="8" stroke-linecap="round"/>
    <path d="M184 96l24 16-24 16" fill="none" stroke="#111" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
    <text x="132" y="90" text-anchor="middle" fill="#111" font-size="24" font-weight="700">150 m</text>
  `),
  e4: tableSvg(`<text x="160" y="126" text-anchor="middle" fill="#111" font-size="48" font-weight="800">2 km</text>`),
  e7a: tableSvg(`
    <path d="M90 112h140" stroke="#111" stroke-width="10" stroke-linecap="round"/>
    <path d="M208 92l24 20-24 20" fill="none" stroke="#111" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>
  `),
  e7b: tableSvg(`
    <path d="M96 138h84" stroke="#111" stroke-width="10" stroke-linecap="round"/>
    <path d="M180 138V88h40" stroke="#111" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
    <path d="M202 68l20 20-20 20" fill="none" stroke="#111" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>
  `),
  e8a: tableSvg(`
    <path d="M112 142V82" stroke="#111" stroke-width="10" stroke-linecap="round"/>
    <path d="M112 82h96" stroke="#111" stroke-width="10" stroke-linecap="round"/>
    <path d="M188 62l20 20-20 20" fill="none" stroke="#111" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>
  `),
  e8c: tableSvg(`
    <path d="M208 142V82" stroke="#111" stroke-width="10" stroke-linecap="round"/>
    <path d="M112 142h96" stroke="#111" stroke-width="10" stroke-linecap="round"/>
    <path d="M132 122l-20 20 20 20" fill="none" stroke="#111" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>
  `),
  e9: tableSvg(`
    <rect x="102" y="100" width="96" height="34" rx="6" fill="none" stroke="#111" stroke-width="7"/>
    <rect x="118" y="82" width="42" height="24" rx="4" fill="none" stroke="#111" stroke-width="7"/>
    <circle cx="126" cy="142" r="12" fill="none" stroke="#111" stroke-width="7"/>
    <circle cx="182" cy="142" r="12" fill="none" stroke="#111" stroke-width="7"/>
  `),
  e13: tableSvg(`<text x="160" y="124" text-anchor="middle" fill="#111" font-size="26" font-weight="800">MIMO ZÁSOBOVÁNÍ</text>`),
};

export const categories = [
  {
    id: "vystrazne",
    title: "Výstražné",
    description: "Značky, které tě dopředu upozorní na nebezpečí nebo změnu situace.",
  },
  {
    id: "prednost",
    title: "Značky upravující přednost",
    description: "Říkají, kdo má přednost a kdy musíš zpomalit nebo zastavit.",
  },
  {
    id: "zakazove",
    title: "Zákazové",
    description: "Zakazují určitý směr, vjezd nebo chování řidiče.",
  },
  {
    id: "prikazove",
    title: "Příkazové",
    description: "Naopak přikazují, kudy jet nebo jak se na místě chovat.",
  },
  {
    id: "vodorovne",
    title: "Vodorovné",
    description: "Značení přímo na vozovce, které vede směr jízdy a upozorňuje na pravidla.",
  },
  {
    id: "dodatkove",
    title: "Dodatkové tabulky",
    description: "Upřesňují, kde značka platí, pro koho platí nebo jak dlouho.",
  },
];

export const signs = [
  {
    id: "a1a",
    code: "A 1a",
    category: "vystrazne",
    nameCz: "Zatáčka vpravo",
    shortMeaning: "Upozorňuje, že se blíží ostřejší zatáčka doprava.",
    detailsCz: "Je dobré ubrat plyn a počítat s horším výhledem i menším prostorem pro chybu.",
    imageUrl: commons("Czech_Republic_road_sign_A_1a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a1b",
    code: "A 1b",
    category: "vystrazne",
    nameCz: "Zatáčka vlevo",
    shortMeaning: "Upozorňuje, že se blíží ostřejší zatáčka doleva.",
    detailsCz: "Smysl je stejný jako u pravé zatáčky: zpomalit a nepřijíždět do ní zbytečně rychle.",
    imageUrl: commons("Czech_Republic_road_sign_A_1b.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a3",
    code: "A 3",
    category: "vystrazne",
    nameCz: "Křižovatka",
    shortMeaning: "Upozorňuje na křižovatku bez zvláštní úpravy přednosti.",
    detailsCz: "Řidič má být připravený sledovat situaci a použít běžná pravidla přednosti.",
    imageUrl: commons("Czech_Republic_road_sign_A_3.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a4",
    code: "A 4",
    category: "vystrazne",
    nameCz: "Křižovatka s kruhovým objezdem",
    shortMeaning: "Dává vědět, že se blíží kruhový objezd.",
    detailsCz: "Pomáhá řidiči včas zpomalit a připravit se na správné zařazení a dávání přednosti.",
    imageUrl: commons("Czech_Republic_road_sign_A_4.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a5a",
    code: "A 5a",
    category: "vystrazne",
    nameCz: "Nebezpečné klesání",
    shortMeaning: "Varuje před prudkým klesáním vozovky.",
    detailsCz: "Na takovém úseku je potřeba hlídat rychlost a často si pomoci nižším převodovým stupněm.",
    imageUrl: commons("Czech_Republic_road_sign_A_5a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a5b",
    code: "A 5b",
    category: "vystrazne",
    nameCz: "Nebezpečné stoupání",
    shortMeaning: "Varuje před prudkým stoupáním.",
    detailsCz: "Řidič by měl počítat s tím, že vozidlo může ztrácet rychlost a některá auta pojedou pomaleji.",
    imageUrl: commons("Czech_Republic_road_sign_A_5b.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a7a",
    code: "A 7a",
    category: "vystrazne",
    nameCz: "Nerovnost vozovky",
    shortMeaning: "Upozorňuje na hrboly, díry nebo jinak špatný povrch.",
    detailsCz: "Je lepší zpomalit, aby auto neztratilo stabilitu a aby řidič nepřehlédl další překážku.",
    imageUrl: commons("Czech_Republic_road_sign_A_7a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a8",
    code: "A 8",
    category: "vystrazne",
    nameCz: "Nebezpečí smyku",
    shortMeaning: "Varuje, že na úseku může auto snadno dostat smyk.",
    detailsCz: "Často jde o kluzký povrch, vodu, led nebo nečekaně zrádnou zatáčku.",
    imageUrl: commons("Czech_Republic_road_sign_A_8.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a11",
    code: "A 11",
    category: "vystrazne",
    nameCz: "Přechod pro chodce",
    shortMeaning: "Upozorňuje, že se blíží přechod pro chodce.",
    detailsCz: "Řidič má zpozornět a být připraven včas zastavit, pokud někdo chce přecházet.",
    imageUrl: commons("Czech_Republic_road_sign_A_11.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a15",
    code: "A 15",
    category: "vystrazne",
    nameCz: "Práce na silnici",
    shortMeaning: "Varuje před pracemi na silnici a změnou běžné situace.",
    detailsCz: "Může jít o zúžený pruh, dělníky na vozovce nebo dočasné omezení rychlosti.",
    imageUrl: commons("Czech_Republic_road_sign_A_15.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a19",
    code: "A 19",
    category: "vystrazne",
    nameCz: "Cyklisté",
    shortMeaning: "Upozorňuje na místo, kde se mohou objevovat cyklisté.",
    detailsCz: "Často se používá tam, kde cyklisté vjíždějí na vozovku nebo ji kříží.",
    imageUrl: commons("Czech_Republic_road_sign_A_19.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a24",
    code: "A 24",
    category: "vystrazne",
    nameCz: "Náledí",
    shortMeaning: "Varuje před častým výskytem náledí.",
    detailsCz: "Značka připomíná, že i když cesta vypadá normálně, může být velmi kluzká.",
    imageUrl: commons("Czech_Republic_road_sign_A_24.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "a29",
    code: "A 29",
    category: "vystrazne",
    nameCz: "Železniční přejezd se závorami",
    shortMeaning: "Upozorňuje na železniční přejezd, který je chráněný závorami.",
    detailsCz: "Řidič má zpozornět a včas kontrolovat světla, závory i provoz před přejezdem.",
    imageUrl: commons("Czech_Republic_road_sign_A_29.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p1",
    code: "P 1",
    category: "prednost",
    nameCz: "Křižovatka s vedlejší pozemní komunikací",
    shortMeaning: "Ukazuje, že jedeš po hlavní a z boku se připojuje vedlejší silnice.",
    detailsCz: "Pomáhá pochopit, odkud mohou přijíždět auta, která ti mají dát přednost.",
    imageUrl: commons("Czech_Republic_road_sign_P_1.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p2",
    code: "P 2",
    category: "prednost",
    nameCz: "Hlavní pozemní komunikace",
    shortMeaning: "Označuje, že jedeš po hlavní silnici.",
    detailsCz: "Na dalších křižovatkách ti obvykle budou dávat přednost vozidla z vedlejších směrů.",
    imageUrl: commons("CZ-P02_Hlavn%C3%AD_pozemn%C3%AD_komunikace.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p3",
    code: "P 3",
    category: "prednost",
    nameCz: "Konec hlavní pozemní komunikace",
    shortMeaning: "Oznamuje, že hlavní silnice brzy končí.",
    detailsCz: "Na následující křižovatce už nemusíš mít přednost, takže je potřeba číst další značení.",
    imageUrl: commons("CZ-P03_Konec_hlavn%C3%AD_pozemn%C3%AD_komunikace.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p4",
    code: "P 4",
    category: "prednost",
    nameCz: "Dej přednost v jízdě!",
    shortMeaning: "Musíš dát přednost vozidlům na hlavní.",
    detailsCz: "Není nutné vždy zastavit, ale jen pokud to situace opravdu dovoluje bezpečně.",
    imageUrl: commons("Czech_Republic_road_sign_P_4.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p5",
    code: "P 5",
    category: "prednost",
    nameCz: "Dej přednost v jízdě tramvaji!",
    shortMeaning: "Přikazuje dát přednost tramvaji.",
    detailsCz: "Používá se tam, kde by to bez značky nemuselo být řidiči jasné.",
    imageUrl: commons("P05_CZ.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p6",
    code: "P 6",
    category: "prednost",
    nameCz: "Stůj, dej přednost v jízdě!",
    shortMeaning: "Musíš úplně zastavit a pak dát přednost.",
    detailsCz: "Nestačí jen zpomalit. Auto musí skutečně stát, i když nic nejede.",
    imageUrl: commons("Czech_Republic_road_sign_P_6.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p7",
    code: "P 7",
    category: "prednost",
    nameCz: "Přednost protijedoucích vozidel",
    shortMeaning: "Musíš pustit auta jedoucí proti tobě.",
    detailsCz: "Typicky tam, kde je silnice zúžená a dvě auta se vedle sebe nevejdou.",
    imageUrl: commons("P07_CZ.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "p8",
    code: "P 8",
    category: "prednost",
    nameCz: "Přednost před protijedoucími vozidly",
    shortMeaning: "V úzkém místě máš přednost ty.",
    detailsCz: "I tak je potřeba jet opatrně a počítat s tím, že druhý řidič může situaci vyhodnotit špatně.",
    imageUrl: commons("CZ_road_sign_P-8.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b1",
    code: "B 1",
    category: "zakazove",
    nameCz: "Zákaz vjezdu všech vozidel (v obou směrech)",
    shortMeaning: "Do takto označené silnice nesmí vjet žádné vozidlo.",
    detailsCz: "Zákaz platí pro oba směry, pokud není doplněn výjimkou na dodatkové tabulce.",
    imageUrl: commons("CZ_road_sign_B-1.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b2",
    code: "B 2",
    category: "zakazove",
    nameCz: "Zákaz vjezdu všech vozidel",
    shortMeaning: "Jde o klasický zákaz vjezdu do protisměru.",
    detailsCz: "Nejčastěji označuje, že z této strany nesmíš do jednosměrky.",
    imageUrl: commons("CZ_road_sign_B-2.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b4",
    code: "B 4",
    category: "zakazove",
    nameCz: "Zákaz vjezdu nákladních automobilů",
    shortMeaning: "Zakazuje vjezd nákladním autům.",
    detailsCz: "Často chrání užší centrum obce, most nebo ulici, kam se těžší auta nehodí.",
    imageUrl: commons("B04cr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b5",
    code: "B 5",
    category: "zakazove",
    nameCz: "Zákaz vjezdu autobusů",
    shortMeaning: "Zakazuje vjezd autobusům.",
    detailsCz: "Používá se tam, kde by autobus mohl překážet nebo by se nevešel bezpečně projet.",
    imageUrl: commons("B05cr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b6",
    code: "B 6",
    category: "zakazove",
    nameCz: "Zákaz vjezdu traktorů",
    shortMeaning: "Zakazuje vjezd traktorům a podobným strojům.",
    detailsCz: "Pomáhá oddělit pomalou zemědělskou techniku od míst, kde by zdržovala nebo byla nebezpečná.",
    imageUrl: commons("B06cr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b7",
    code: "B 7",
    category: "zakazove",
    nameCz: "Zákaz vjezdu motocyklů",
    shortMeaning: "Zakazuje vjezd motocyklům.",
    detailsCz: "Může chránit klidnou oblast nebo místo, kde jsou motocykly zvlášť rizikové.",
    imageUrl: commons("B07cr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b8",
    code: "B 8",
    category: "zakazove",
    nameCz: "Zákaz vjezdu jízdních kol",
    shortMeaning: "Zakazuje vjezd cyklistům.",
    detailsCz: "Cyklista musí zvolit jinou trasu nebo kolo vést tam, kde je to dovoleno.",
    imageUrl: commons("B08cr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b20a",
    code: "B 20a",
    category: "zakazove",
    nameCz: "Nejvyšší dovolená rychlost",
    shortMeaning: "Udává maximální rychlost, kterou nesmíš překročit.",
    detailsCz: "Platí od značky dál, dokud ji nezruší jiná značka nebo křižovatka podle pravidel.",
    imageUrl: commons("B20acr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b21a",
    code: "B 21a",
    category: "zakazove",
    nameCz: "Zákaz předjíždění",
    shortMeaning: "Zakazuje předjíždět motorová vozidla.",
    detailsCz: "Má zabránit riskantnímu předjíždění v místech s malým rozhledem nebo vyšším nebezpečím.",
    imageUrl: commons("B21a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b24a",
    code: "B 24a",
    category: "zakazove",
    nameCz: "Zákaz odbočování vpravo",
    shortMeaning: "Na nejbližším místě nesmíš odbočit doprava.",
    detailsCz: "Používá se třeba tam, kde by odbočení vedlo do jednosměrky nebo do nebezpečného prostoru.",
    imageUrl: commons("B24acz.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b24b",
    code: "B 24b",
    category: "zakazove",
    nameCz: "Zákaz odbočování vlevo",
    shortMeaning: "Na nejbližším místě nesmíš odbočit doleva.",
    detailsCz: "Často chrání provoz tam, kde by levé odbočení moc blokovalo nebo bylo nebezpečné.",
    imageUrl: commons("B24bcz.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b25",
    code: "B 25",
    category: "zakazove",
    nameCz: "Zákaz otáčení",
    shortMeaning: "Zakazuje otočit se do protisměru.",
    detailsCz: "Neznamená zákaz odbočení, ale zákaz úplného obrácení směru jízdy.",
    imageUrl: commons("B25cr.jpg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b26",
    code: "B 26",
    category: "zakazove",
    nameCz: "Konec všech zákazů",
    shortMeaning: "Ukončuje předchozí zákazy a omezení pro jedoucí vozidla.",
    detailsCz: "Typicky ruší například omezení rychlosti nebo zákaz předjíždění, pokud ještě platily.",
    imageUrl: commons("CZ_road_sign_B-26.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b28",
    code: "B 28",
    category: "zakazove",
    nameCz: "Zákaz zastavení",
    shortMeaning: "Nesmíš tu ani krátce zastavit.",
    detailsCz: "Platí to i pro velmi krátké stání, třeba jen kvůli vysazení člověka.",
    imageUrl: commons("CZ_road_sign_B-28.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "b29",
    code: "B 29",
    category: "zakazove",
    nameCz: "Zákaz stání",
    shortMeaning: "Můžeš zastavit, ale nesmíš tu stát delší dobu.",
    detailsCz: "Typicky je možné rychlé naložení nebo vysazení, ale ne běžné parkování.",
    imageUrl: commons("CZ_road_sign_B-29.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c1",
    code: "C 1",
    category: "prikazove",
    nameCz: "Kruhový objezd",
    shortMeaning: "Přikazuje jet po kruhovém objezdu ve směru šipek.",
    detailsCz: "Značka řeší směr jízdy uvnitř kruháče, ne sama o sobě pravidla přednosti.",
    imageUrl: commons("CZ_road_sign_C01.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c2a",
    code: "C 2a",
    category: "prikazove",
    nameCz: "Přikázaný směr jízdy přímo",
    shortMeaning: "Musíš pokračovat rovně.",
    detailsCz: "Jiný směr je zakázaný, pokud není zvlášť povolený dalším značením.",
    imageUrl: commons("CZ_road_sign_C02a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c2b",
    code: "C 2b",
    category: "prikazove",
    nameCz: "Přikázaný směr jízdy vpravo",
    shortMeaning: "Musíš odbočit doprava.",
    detailsCz: "Používá se tam, kde je jiný průjezd nežádoucí nebo nebezpečný.",
    imageUrl: commons("CZ_road_sign_C02b.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c2c",
    code: "C 2c",
    category: "prikazove",
    nameCz: "Přikázaný směr jízdy vlevo",
    shortMeaning: "Musíš odbočit doleva.",
    detailsCz: "Stejně jako jiné příkazové směrové značky jasně říká, kudy se má pokračovat.",
    imageUrl: commons("CZ_road_sign_C02c.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c2d",
    code: "C 2d",
    category: "prikazove",
    nameCz: "Přikázaný směr jízdy přímo a vpravo",
    shortMeaning: "Smíš jet buď rovně, nebo doprava.",
    detailsCz: "Ostatní směry jsou zakázané.",
    imageUrl: commons("CZ_road_sign_C02d.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c3a",
    code: "C 3a",
    category: "prikazove",
    nameCz: "Přikázaný směr jízdy zde vpravo",
    shortMeaning: "Přikazuje objet místo nebo odbočit doprava hned u značky.",
    detailsCz: "Důraz je na bezprostřední směr, ne až někde dál na křižovatce.",
    imageUrl: commons("CZ_road_sign_C03a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c4c",
    code: "C 4c",
    category: "prikazove",
    nameCz: "Přikázaný směr objíždění vpravo a vlevo",
    shortMeaning: "Překážku můžeš objet zleva i zprava.",
    detailsCz: "Typicky jde o ostrůvek nebo jiné dělení provozu uprostřed silnice.",
    imageUrl: commons("CZ_road_sign_C04c.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c5a",
    code: "C 5a",
    category: "prikazove",
    nameCz: "Sněhové řetězy",
    shortMeaning: "Bez nasazených řetězů dál nesmíš.",
    detailsCz: "Používá se hlavně v zimních horských úsecích, kde by jinak hrozilo zablokování silnice.",
    imageUrl: commons("CZ_road_sign_C05a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c6a",
    code: "C 6a",
    category: "prikazove",
    nameCz: "Nejnižší dovolená rychlost",
    shortMeaning: "Přikazuje jet alespoň vyznačenou minimální rychlostí.",
    detailsCz: "Neplatí to, pokud by taková rychlost byla kvůli situaci nebezpečná.",
    imageUrl: commons("CZ_road_sign_C06a.30.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c7a",
    code: "C 7a",
    category: "prikazove",
    nameCz: "Stezka pro chodce",
    shortMeaning: "Vyhrazuje cestu hlavně pro chodce.",
    detailsCz: "Jiní účastníci tam obvykle nesmí, pokud to není výslovně dovoleno.",
    imageUrl: commons("CZ_road_sign_C07a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c8a",
    code: "C 8a",
    category: "prikazove",
    nameCz: "Stezka pro cyklisty",
    shortMeaning: "Vyhrazuje cestu pro cyklisty.",
    detailsCz: "Cyklisté ji mají používat a ostatní tam zpravidla nemají co dělat.",
    imageUrl: commons("CZ_road_sign_C08a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c9a",
    code: "C 9a",
    category: "prikazove",
    nameCz: "Stezka pro chodce a cyklisty společná",
    shortMeaning: "Chodci i cyklisté používají jeden společný prostor.",
    detailsCz: "Je potřeba být ohleduplný, protože se obě skupiny pohybují vedle sebe bez oddělení.",
    imageUrl: commons("CZ_road_sign_C09a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c10a",
    code: "C 10a",
    category: "prikazove",
    nameCz: "Stezka pro chodce a cyklisty dělená",
    shortMeaning: "Stezka je rozdělena na část pro chodce a část pro cyklisty.",
    detailsCz: "Každý by měl držet svůj pruh podle symbolů na značce.",
    imageUrl: commons("CZ_road_sign_C10a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c13a",
    code: "C 13a",
    category: "prikazove",
    nameCz: "Rozsviť světla",
    shortMeaning: "Přikazuje rozsvítit světla.",
    detailsCz: "Používá se v místech, kde je potřeba řidiče na světla zvlášť upozornit, třeba před tunelem.",
    imageUrl: commons("CZ_road_sign_C13a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "c15a",
    code: "C 15a",
    category: "prikazove",
    nameCz: "Zimní výbava",
    shortMeaning: "Bez zimní výbavy se do úseku nesmí pokračovat.",
    detailsCz: "Smyslem je zabránit tomu, aby nevhodně obutá auta blokovala provoz na sněhu nebo ledu.",
    imageUrl: commons("CZ_road_sign_C-15a.svg"),
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v1a",
    code: "V 1a",
    category: "vodorovne",
    nameCz: "Podélná čára souvislá",
    shortMeaning: "Plná čára, kterou se nesmí běžně přejíždět.",
    detailsCz: "Odděluje směry nebo pruhy tam, kde by přejetí bylo nebezpečné.",
    imageUrl: horizontalImages.v1a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v2a",
    code: "V 2a",
    category: "vodorovne",
    nameCz: "Podélná čára přerušovaná",
    shortMeaning: "Přerušovaná čára, kterou můžeš za běžných pravidel přejet.",
    detailsCz: "Používá se třeba mezi jízdními pruhy nebo tam, kde je změna pruhu dovolená.",
    imageUrl: horizontalImages.v2a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v5",
    code: "V 5",
    category: "vodorovne",
    nameCz: "Příčná čára souvislá",
    shortMeaning: "Vyznačuje hranici, kam by mělo vozidlo dojet před křižovatkou.",
    detailsCz: "Často pomáhá jasně ukázat místo zastavení nebo hranici křižovatky.",
    imageUrl: horizontalImages.v5,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v6b",
    code: "V 6b",
    category: "vodorovne",
    nameCz: "Příčná čára souvislá s nápisem STOP",
    shortMeaning: "Ukazuje místo, kde musí řidič skutečně zastavit.",
    detailsCz: "Používá se společně se značkou STOP, aby bylo jasné, kde se má stát.",
    imageUrl: horizontalImages.v6b,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v7a",
    code: "V 7a",
    category: "vodorovne",
    nameCz: "Přechod pro chodce",
    shortMeaning: "Známá zebra pro chodce.",
    detailsCz: "Řidič musí počítat s tím, že tudy chodci přecházejí a mají tu zvláštní ochranu.",
    imageUrl: horizontalImages.v7a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v8a",
    code: "V 8a",
    category: "vodorovne",
    nameCz: "Přejezd pro cyklisty",
    shortMeaning: "Místo určené pro přejezd cyklistů přes silnici.",
    detailsCz: "Vypadá jinak než zebra a připomíná, že tudy mohou silnici křížit kola.",
    imageUrl: horizontalImages.v8a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v9a",
    code: "V 9a",
    category: "vodorovne",
    nameCz: "Směrové šipky",
    shortMeaning: "Šipky na silnici ukazují, jak se máš zařadit a kam smíš pokračovat.",
    detailsCz: "Pomáhají řidiči ještě před křižovatkou pochopit správný pruh i povolený směr.",
    imageUrl: horizontalImages.v9a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v12b",
    code: "V 12b",
    category: "vodorovne",
    nameCz: "Žluté zkřížené čáry",
    shortMeaning: "Do této vyznačené plochy nemáš vjíždět, pokud bys v ní musel stát.",
    detailsCz: "Používá se v místech, která je potřeba nechat volná, třeba u křižovatek.",
    imageUrl: horizontalImages.v12b,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v14",
    code: "V 14",
    category: "vodorovne",
    nameCz: "Jízdní pruh pro cyklisty",
    shortMeaning: "Označuje pruh vyhrazený pro kola.",
    detailsCz: "Řidič auta má počítat s cyklisty v tomto prostoru a zbytečně jim do pruhu nevjíždět.",
    imageUrl: horizontalImages.v14,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "v15",
    code: "V 15",
    category: "vodorovne",
    nameCz: "Nápis na vozovce",
    shortMeaning: "Doplňující text přímo na vozovce upřesňuje situaci před tebou.",
    detailsCz: "Může připomínat povinnost zastavit, školu, bus pruh nebo jinou důležitou informaci.",
    imageUrl: horizontalImages.v15,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e1",
    code: "E 1",
    category: "dodatkove",
    nameCz: "Počet",
    shortMeaning: "Upřesňuje skutečný počet něčeho, třeba zatáček nebo pruhů.",
    detailsCz: "Sama o sobě nic nenařizuje, jen doplňuje význam hlavní značky.",
    imageUrl: supplementaryImages.e1,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e3a",
    code: "E 3a",
    category: "dodatkove",
    nameCz: "Vzdálenost",
    shortMeaning: "Říká, jak daleko odtud začne platit hlavní značka.",
    detailsCz: "Díky tomu víš, že omezení nebo nebezpečí nezačíná hned u tabulky.",
    imageUrl: supplementaryImages.e3a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e4",
    code: "E 4",
    category: "dodatkove",
    nameCz: "Délka úseku",
    shortMeaning: "Ukazuje, jak dlouho zákaz, příkaz nebo upozornění trvá.",
    detailsCz: "Pomáhá odhadnout, jak daleko bude omezení pokračovat.",
    imageUrl: supplementaryImages.e4,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e7a",
    code: "E 7a",
    category: "dodatkove",
    nameCz: "Směrová šipka pro směr přímo",
    shortMeaning: "Upřesňuje, že se hlavní značka vztahuje na směr přímo.",
    detailsCz: "Hodí se tam, kde by bez šipky nebylo jasné, kterého směru se omezení týká.",
    imageUrl: supplementaryImages.e7a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e7b",
    code: "E 7b",
    category: "dodatkove",
    nameCz: "Směrová šipka pro odbočení",
    shortMeaning: "Upřesňuje, že značka platí pro odbočující směr.",
    detailsCz: "Často se používá třeba před železničním přejezdem nebo zvláštním omezením na vedlejší cestě.",
    imageUrl: supplementaryImages.e7b,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e8a",
    code: "E 8a",
    category: "dodatkove",
    nameCz: "Začátek úseku",
    shortMeaning: "Říká, že omezení začíná právě od tohoto místa dál.",
    detailsCz: "Typicky se přidává k zákazu zastavení nebo stání.",
    imageUrl: supplementaryImages.e8a,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e8c",
    code: "E 8c",
    category: "dodatkove",
    nameCz: "Konec úseku",
    shortMeaning: "Ukazuje, kde omezený úsek končí.",
    detailsCz: "Díky tomu víš, od kterého místa už značka dál neplatí.",
    imageUrl: supplementaryImages.e8c,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e9",
    code: "E 9",
    category: "dodatkove",
    nameCz: "Druh vozidla",
    shortMeaning: "Upřesňuje, na jaký druh vozidla se značka vztahuje.",
    detailsCz: "Například může říkat, že omezení platí jen pro náklaďáky nebo jen pro kola.",
    imageUrl: supplementaryImages.e9,
    sourceUrl: WIKI_SOURCE,
  },
  {
    id: "e13",
    code: "E 13",
    category: "dodatkove",
    nameCz: "Text nebo symbol",
    shortMeaning: "Doplňuje značku textem nebo jednoduchým symbolem.",
    detailsCz: "Na tabulce bývají například výjimky, čas platnosti nebo upřesnění, pro koho značka platí.",
    imageUrl: supplementaryImages.e13,
    sourceUrl: WIKI_SOURCE,
  },
];
